<a href="https://colab.research.google.com/github/Suman18-bit/NLP_CHALANGES/blob/main/Sentiment_analysis_with_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%capture
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00331/sentiment%20labelled%20sentences.zip

In [ ]:
!unzip '/content/sentiment labelled sentences.zip'

Archive:  /content/sentiment labelled sentences.zip
   creating: sentiment labelled sentences/
  inflating: sentiment labelled sentences/.DS_Store
   creating: __MACOSX/
   creating: __MACOSX/sentiment labelled sentences/
  inflating: __MACOSX/sentiment labelled sentences/._.DS_Store
  inflating: sentiment labelled sentences/amazon_cells_labelled.txt
  inflating: sentiment labelled sentences/imdb_labelled.txt
  inflating: __MACOSX/sentiment labelled sentences/._imdb_labelled.txt
  inflating: sentiment labelled sentences/readme.txt
  inflating: __MACOSX/sentiment labelled sentences/._readme.txt
  inflating: sentiment labelled sentences/yelp_labelled.txt
  inflating: __MACOSX/._sentiment labelled sentences

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv('/content/sentiment labelled sentences/amazon_cells_labelled.txt',delimiter='\t',names=['review','labelled_sentiment'])
df2 = pd.read_csv('/content/sentiment labelled sentences/imdb_labelled.txt',delimiter='\t',names=['review','labelled_sentiment'])
df3 = pd.read_csv('/content/sentiment labelled sentences/yelp_labelled.txt',delimiter='\t',names=['review','labelled_sentiment'])

In [ ]:
df = pd.concat([df1,df2,df3],axis=0,ignore_index=True)

In [ ]:
df.head()

                                              review  labelled_sentiment
0  So there is no way for me to plug it in here i...                   0
1                        Good case, Excellent value.                   1
2                             Great for the jawbone.                   1
3  Tied to charger for conversations lasting more...                   0
4                                  The mic is great.                   1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2748 entries, 0 to 2747
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   review              2748 non-null   object
 1   labelled_sentiment  2748 non-null   int64
dtypes: int64(1), object(1)
memory usage: 43.1+ KB

In [ ]:
from transformers import pipeline

In [ ]:
distilbert_classifier = pipeline('sentiment-analysis',truncation = True)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
print(df['review'][1])
test = distilbert_classifier(df['review'][1])
print(test)

Good case, Excellent value.
[{'label': 'POSITIVE', 'score': 0.9998685121536255}]

In [ ]:
test[0]['label']

'POSITIVE'

In [ ]:
test[0]['score']

0.9998685121536255

In [ ]:
df.head()

                                              review  labelled_sentiment
0  So there is no way for me to plug it in here i...                   0
1                        Good case, Excellent value.                   1
2                             Great for the jawbone.                   1
3  Tied to charger for conversations lasting more...                   0
4                                  The mic is great.                   1

In [ ]:
df['distilbert_sentiment'] = df['review'].apply(lambda x : distilbert_classifier(x))

In [ ]:
df.head()

,review,labelled_sentiment,distilbert_sentiment
0,So there is no way for me to plug it in here i...,0,"[{'label': 'NEGATIVE', 'score': 0.999408602714..."
1,"Good case, Excellent value.",1,"[{'label': 'POSITIVE', 'score': 0.999868512153..."
2,Great for the jawbone.,1,"[{'label': 'POSITIVE', 'score': 0.999779641628..."
3,Tied to charger for conversations lasting more...,0,"[{'label': 'NEGATIVE', 'score': 0.999404191970..."
4,The mic is great.,1,"[{'label': 'POSITIVE', 'score': 0.999868988990..."

In [ ]:
roberta_classifier = pipeline("sentiment-analysis",model="siebert/sentiment-roberta-large-english",truncation = True)

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/256 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

In [ ]:
df['roberta_sentiment'] = df['review'].apply(lambda x : roberta_classifier(x))

In [ ]:
df.head()

,review,labelled_sentiment,distilbert_sentiment,roberta_sentiment
0,So there is no way for me to plug it in here i...,0,"[{'label': 'NEGATIVE', 'score': 0.999408602714...","[{'label': 'NEGATIVE', 'score': 0.999331653118..."
1,"Good case, Excellent value.",1,"[{'label': 'POSITIVE', 'score': 0.999868512153...","[{'label': 'POSITIVE', 'score': 0.998826086521..."
2,Great for the jawbone.,1,"[{'label': 'POSITIVE', 'score': 0.999779641628...","[{'label': 'POSITIVE', 'score': 0.998665452003..."
3,Tied to charger for conversations lasting more...,0,"[{'label': 'NEGATIVE', 'score': 0.999404191970...","[{'label': 'NEGATIVE', 'score': 0.999490618705..."
4,The mic is great.,1,"[{'label': 'POSITIVE', 'score': 0.999868988990...","[{'label': 'POSITIVE', 'score': 0.998643219470..."

In [ ]:
bert_classifier = pipeline("sentiment-analysis",model="barissayil/bert-sentiment-analysis-sst",truncation = True)

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: barissayil/bert-sentiment-analysis-sst
Key               | Status     |
------------------+------------+-
cls_layer.weight  | UNEXPECTED |
cls_layer.bias    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
df['bert_sentiment'] = df['review'].apply(lambda x : bert_classifier(x))

In [ ]:
df.head()

,review,labelled_sentiment,distilbert_sentiment,roberta_sentiment,bert_sentiment
0,So there is no way for me to plug it in here i...,0,"[{'label': 'NEGATIVE', 'score': 0.999408602714...","[{'label': 'NEGATIVE', 'score': 0.999331653118...","[{'label': 'LABEL_0', 'score': 0.5564930438995..."
1,"Good case, Excellent value.",1,"[{'label': 'POSITIVE', 'score': 0.999868512153...","[{'label': 'POSITIVE', 'score': 0.998826086521...","[{'label': 'LABEL_0', 'score': 0.5014965534210..."
2,Great for the jawbone.,1,"[{'label': 'POSITIVE', 'score': 0.999779641628...","[{'label': 'POSITIVE', 'score': 0.998665452003...","[{'label': 'LABEL_0', 'score': 0.5288613438606..."
3,Tied to charger for conversations lasting more...,0,"[{'label': 'NEGATIVE', 'score': 0.999404191970...","[{'label': 'NEGATIVE', 'score': 0.999490618705...","[{'label': 'LABEL_0', 'score': 0.5638469457626..."
4,The mic is great.,1,"[{'label': 'POSITIVE', 'score': 0.999868988990...","[{'label': 'POSITIVE', 'score': 0.998643219470...","[{'label': 'LABEL_0', 'score': 0.5386167764663..."