In [6]:
from sklearn.datasets import fetch_20newsgroups
import pandas as pd
from pprint import pprint

In [7]:
dataset = fetch_20newsgroups(subset="all",shuffle=True, random_state=32, remove=('headers', 'footers', 'quotes'))

In [8]:
dataset.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [9]:
# dataset['data']

In [10]:
pprint(dataset.target_names)

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [11]:
len(dataset.target_names)

20

In [12]:
dataset.target.shape

(18846,)

In [13]:
dataset.filenames.shape

(18846,)

In [14]:
dataset_df = pd.DataFrame({"News":dataset.data, "Label":dataset.target})

In [15]:
dataset_df.head()

                                                News  Label
0  :I'm not sure why you don't consider it an opt...     18
1  \n\nPoor 'Poly'. I see you're preparing the gr...     17
2  \nYes, Colin... I have to agree with you here....     10
3  \n\n\n\nIt has been a while since I knew the e...     12
4  \n\n\nWell, if you want to stick the nose of y...      7

In [16]:
dataset_df['Label_Name']=dataset_df['Label'].apply(lambda x:dataset.target_names[x])

In [17]:
dataset_df.head()

,News,Label,Label_Name
0,:I'm not sure why you don't consider it an opt...,18,talk.politics.misc
1,\n\nPoor 'Poly'. I see you're preparing the gr...,17,talk.politics.mideast
2,"\nYes, Colin... I have to agree with you here....",10,rec.sport.hockey
3,\n\n\n\nIt has been a while since I knew the e...,12,sci.electronics
4,"\n\n\nWell, if you want to stick the nose of y...",7,rec.autos

In [18]:
!pip install -U gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 82.7 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [19]:
import gensim

In [20]:
from gensim.utils import tokenize

In [21]:
from gensim.parsing.preprocessing import preprocess_string,strip_tags,strip_punctuation,strip_numeric,remove_stopwords,strip_short
from gensim.corpora.dictionary import Dictionary
from gensim import models

In [22]:
help(preprocess_string)

Help on function preprocess_string in module gensim.parsing.preprocessing:

preprocess_string(s, filters=[<function <lambda> at 0x7efa02db4180>, <function strip_tags at 0x7efa02dbbb00>, <function strip_punctuation at 0x7efa0549d8a0>, <function strip_multiple_whitespaces at 0x7efa02dbbe20>, <function strip_numeric at 0x7efa02dbbce0>, <function remove_stopwords at 0x7efa0550c220>, <function strip_short at 0x7efa02dbbba0>, <function stem_text at 0x7efa02dbbf60>])
    Apply list of chosen filters to `s`.

    Default list of filters:

    * :func:`~gensim.parsing.preprocessing.strip_tags`,
    * :func:`~gensim.parsing.preprocessing.strip_punctuation`,
    * :func:`~gensim.parsing.preprocessing.strip_multiple_whitespaces`,
    * :func:`~gensim.parsing.preprocessing.strip_numeric`,
    * :func:`~gensim.parsing.preprocessing.remove_stopwords`,
    * :func:`~gensim.parsing.preprocessing.strip_short`,
    * :func:`~gensim.parsing.preprocessing.stem_text`.

    Parameters
    ----------
    s : str
    filters: list of functions, optional

    Returns
    -------
    list of str
        Processed strings (cleaned).

    Examples
    --------
    .. sourcecode:: pycon

        >>> from gensim.parsing.preprocessing import preprocess_string
        >>> preprocess_string("<i>Hel 9lo</i> <b>Wo9 rld</b>! Th3     weather_is really g00d today, isn't it?")
        [u'hel', u'rld', u'weather', u'todai', u'isn']
        >>>
        >>> s = "<i>Hel 9lo</i> <b>Wo9 rld</b>! Th3     weather_is really g00d today, isn't it?"
        >>> CUSTOM_FILTERS = [lambda x: x.lower(), strip_tags, strip_punctuation]
        >>> preprocess_string(s, CUSTOM_FILTERS)
        [u'hel', u'9lo', u'wo9', u'rld', u'th3', u'weather', u'is', u'really', u'g00d', u'today', u'isn', u't', u'it']

In [23]:
dataset_df['Clean_news'] = dataset_df['News'].apply(preprocess_string)

In [24]:
dataset_df.head()

,News,Label,Label_Name,Clean_news
0,:I'm not sure why you don't consider it an opt...,18,talk.politics.misc,"[sure, consid, option, suggest, analysi, left,..."
1,\n\nPoor 'Poly'. I see you're preparing the gr...,17,talk.politics.mideast,"[poor, poli, prepar, groundwork, retreat, arro..."
2,"\nYes, Colin... I have to agree with you here....",10,rec.sport.hockey,"[ye, colin, agre, puck, net, wai, smith, mind,..."
3,\n\n\n\nIt has been a while since I knew the e...,12,sci.electronics,"[knew, electron, ham, radio, rememb, pep, actu..."
4,"\n\n\nWell, if you want to stick the nose of y...",7,rec.autos,"[want, stick, nose, car, ass, foot, semi, supp..."

In [25]:
filter = [lambda x: x.lower(),strip_tags,strip_punctuation,strip_numeric,remove_stopwords,strip_short]
dataset_df['Clean_news'] = dataset_df['News'].apply(lambda x: preprocess_string(x,filter))

In [26]:
dataset_df.head()

,News,Label,Label_Name,Clean_news
0,:I'm not sure why you don't consider it an opt...,18,talk.politics.misc,"[sure, consider, option, suggests, analysis, l..."
1,\n\nPoor 'Poly'. I see you're preparing the gr...,17,talk.politics.mideast,"[poor, poly, preparing, groundwork, retreat, a..."
2,"\nYes, Colin... I have to agree with you here....",10,rec.sport.hockey,"[yes, colin, agree, puck, net, way, smith, min..."
3,\n\n\n\nIt has been a while since I knew the e...,12,sci.electronics,"[knew, electronics, ham, radio, remember, pep,..."
4,"\n\n\nWell, if you want to stick the nose of y...",7,rec.autos,"[want, stick, nose, car, ass, foot, semi, supp..."

In [27]:
dataset_dictionary = Dictionary(dataset_df['Clean_news'])

In [28]:
len(dataset_dictionary)

89057

In [29]:
print(dataset_dictionary.token2id)

{'absurd': 0, 'acting': 1, 'actually': 2, 'add': 3, 'added': 4, 'adults': 5, 'advanced': 6, 'afdc': 7, 'agree': 8, 'analysis': 9, 'approach': 10, 'areas': 11, 'aside': 12, 'attack': 13, 'benefit': 14, 'bit': 15, 'buyer': 16, 'case': 17, 'chance': 18, 'children': 19, 'claim': 20, 'coercion': 21, 'coersive': 22, 'combined': 23, 'committed': 24, 'consequence': 25, 'consider': 26, 'consideration': 27, 'considered': 28, 'considering': 29, 'corrupt': 30, 'cost': 31, 'cover': 32, 'creature': 33, 'cutting': 34, 'dealt': 35, 'decision': 36, 'decisions': 37, 'defense': 38, 'delusion': 39, 'difference': 40, 'diluted': 41, 'directly': 42, 'dispute': 43, 'drunken': 44, 'earlier': 45, 'economic': 46, 'education': 47, 'equivalent': 48, 'event': 49, 'expect': 50, 'explain': 51, 'fact': 52, 'fear': 53, 'feasible': 54, 'feel': 55, 'fit': 56, 'follows': 57, 'free': 58, 'frequently': 59, 'functions': 60, 'geezers': 61, 'general': 62, 'generally': 63, 'generate': 64, 'generating': 65, 'government': 66, 'governments': 67, 'grounds': 68, 'groups': 69, 'guns': 70, 'hair': 71, 'highly': 72, 'hiring': 73, 'hmmm': 74, 'honest': 75, 'idea': 76, 'ignorant': 77, 'ignore': 78, 'impossible': 79, 'individual': 80, 'influence': 81, 'intelligent': 82, 'interesting': 83, 'inventing': 84, 'involve': 85, 'issues': 86, 'laboring': 87, 'learn': 88, 'left': 89, 'let': 90, 'libertarian': 91, 'libertarians': 92, 'licensing': 93, 'lie': 94, 'like': 95, 'likely': 96, 'making': 97, 'mean': 98, 'medicine': 99, 'mention': 100, 'merely': 101, 'minors': 102, 'missed': 103, 'mothers': 104, 'movement': 105, 'necessary': 106, 'newsgroups': 107, 'non': 108, 'okay': 109, 'ones': 110, 'option': 111, 'package': 112, 'particular': 113, 'party': 114, 'patronizing': 115, 'people': 116, 'peril': 117, 'persons': 118, 'philosophy': 119, 'police': 120, 'policies': 121, 'possibility': 122, 'practicing': 123, 'president': 124, 'priciple': 125, 'principle': 126, 'privately': 127, 'programs': 128, 'protectors': 129, 'provides': 130, 'public': 131, 'questionare': 132, 'reasonably': 133, 'regulation': 134, 'regulations': 135, 'regulators': 136, 'remaining': 137, 'required': 138, 'respect': 139, 'responsible': 140, 'revolution': 141, 'revolutionaries': 142, 'sarcasm': 143, 'saw': 144, 'security': 145, 'seller': 146, 'senator': 147, 'seriously': 148, 'small': 149, 'social': 150, 'socialized': 151, 'sorry': 152, 'specific': 153, 'spending': 154, 'state': 155, 'strike': 156, 'strikes': 157, 'substantial': 158, 'suggest': 159, 'suggests': 160, 'support': 161, 'sure': 162, 'surprising': 163, 'tasks': 164, 'teenagers': 165, 'ths': 166, 'time': 167, 'transaction': 168, 'treats': 169, 'try': 170, 'undesirable': 171, 'unlikely': 172, 'unreasonable': 173, 'unworthy': 174, 'vast': 175, 'vote': 176, 'voter': 177, 'votes': 178, 'want': 179, 'wholesale': 180, 'worse': 181, 'wrong': 182, 'years': 183, 'academy': 184, 'acted': 185, 'activities': 186, 'adamof': 187, 'adventures': 188, 'affaires': 189, 'agissements': 190, 'agreements': 191, 'ahalinin': 192, 'aharonian': 193, 'ahmad': 194, 'akarli': 195, 'akboy': 196, 'akgun': 197, 'akin': 198, 'aksin': 199, 'alan': 200, 'alexander': 201, 'alfred': 202, 'alive': 203, 'aliye': 204, 'allen': 205, 'alper': 206, 'altinay': 207, 'amal': 208, 'ambassador': 209, 'american': 210, 'anadolu': 211, 'anasina': 212, 'anasir': 213, 'anatolia': 214, 'andlasmasi': 215, 'andreas': 216, 'angeles': 217, 'ankara': 218, 'annihilation': 219, 'annual': 220, 'antranik': 221, 'appressian': 222, 'apres': 223, 'archives': 224, 'arf': 225, 'arfa': 226, 'argic': 227, 'armenia': 228, 'armenian': 229, 'armenians': 230, 'armenie': 231, 'armeniens': 232, 'army': 233, 'arnold': 234, 'arromdian': 235, 'arromdians': 236, 'arsiv': 237, 'arsivi': 238, 'arthur': 239, 'arts': 240, 'asaf': 241, 'asala': 242, 'asia': 243, 'asian': 244, 'askeri': 245, 'aspirations': 246, 'associate': 247, 'atamian': 248, 'atase': 249, 'atfedilen': 250, 'attempt': 251, 'authors': 252, 'available': 253, 'avant': 254, 'avetis': 255, 'avigdor': 256, 'babiali': 257, 'baikar': 258, 'bakanligi': 259, 'baltimore': 260, 'baris': 261, 'barton': 262, 'basar': 263, 'basbakanlik': 264, 'basim': 265, 'baski': 266, 'baslangicinda': 267, 'battlefields': 268, 'beirut': 269, 'belen': 270, 'belgeler': 271, 'belgeleri': 272, 'belgeleriyle': 273, 'belgelerle': 274, 'berkeley': 275, 'bernard': 276, 'bir': 277, 'birakismasi': 278, 'birinci': 279, 'bizans': 280, 'blackfriars': 281, 'blanco': 282, 'bobbs': 283, 'bodrogligetti': 284, 'boghos': 285, 'bolkovitinof': 286, 'bombay': 287, 'bortnick': 288, 'boston': 289, 'boxes': 290, 'brandeis': 291, 'bristol': 292, 'british': 293, 'bronsart': 294, 'burrill': 295, 'buyuk': 296, 'caesar': 297, 'california': 298, 'caliph': 299, 'cambridge': 300, 'carry': 301, 'caucasian': 302, 'caucasus': 303, 'cause': 304, 'celse': 305, 'cemaat': 306, 'centuries': 307, 'century': 308, 'cevresinde': 309, 'characteristic': 310, 'charles': 311, 'chatnam': 312, 'chester': 313, 'chicago': 314, 'chieftains': 315, 'city': 316, 'claims': 317, 'clair': 318, 'cleveland': 319, 'cokus': 320, 'collections': 321, 'columbia': 322, 'comites': 323, 'commission': 324, 'committee': 325, 'commons': 326, 'complete': 327, 'conference': 328, 'confidential': 329, 'conn': 330, 'connecticut': 331, 'constable': 332, 'constitution': 333, 'correspondence': 334, 'crane': 335, 'crescent': 336, 'crown': 337, 'curzon': 338, 'dahiliye': 339, 'dair': 340, 'dankwart': 341, 'dashnag': 342, 'dashnagtzoutune': 343, 'davison': 344, 'dec': 345, 'defenseless': 346, 'defterdarlik': 347, 'defterleri': 348, 'deliorman': 349, 'demir': 350, 'denny': 351, 'deporting': 352, 'dergisi': 353, 'derlemeler': 354, 'des': 355, 'devlet': 356, 'devleti': 357, 'devrim': 358, 'dewey': 359, 'dictatorship': 360, 'diplomacy': 361, 'diplomatic': 362, 'diplomatiques': 363, 'director': 364, 'disisleri': 365, 'distinguished': 366, 'divan': 367, 'documents': 368, 'dodd': 369, 'dodge': 370, 'dolayi': 371, 'dosyalari': 372, 'dro': 373, 'ducar': 374, 'dunn': 375, 'dunya': 376, 'east': 377, 'eastern': 378, 'ecnebiyye': 379, 'edip': 380, 'edward': 381, 'ege': 382, 'elie': 383, 'elliot': 384, 'emeritus': 385, 'eminent': 386, 'empire': 387, 'encumeni': 388, 'end': 389, 'english': 390, 'ensuing': 391, 'entered': 392, 'entire': 393, 'entrangeres': 394, 'ercikan': 395, 'ermeni': 396, 'ermeniler': 397, 'ermenilerce': 398, 'ermenilerden': 399, 'ermenilerin': 400, 'ernest': 401, 'eroglu': 402, 'esas': 403, 'eshnanie': 404, 'europe': 405, 'evans': 406, 'evolutions': 407, 'evrak': 408, 'evraki': 409, 'evvel': 410, 'existent': 411, 'eyewitnesses': 412, 'fahrettin': 413, 'fall': 414, 'famous': 415, 'farah': 416, 'farrar': 417, 'fascist': 418, 'felix': 419, 'fertig': 420, 'feruz': 421, 'field': 422, 'fight': 423, 'fighters': 424, 'files': 425, 'fisher': 426, 'flocked': 427, 'foreign': 428, 'french': 429, 'gayr': 430, 'gazigiray': 431, 'genocide': 432, 'george': 433, 'gezisi': 434, 'girisi': 435, 'gizli': 436, 'goes': 437, 'golden': 438, 'goodrich': 439, 'gorduklerimiz': 440, 'got': 441, 'gothard': 442, 'gozen': 443, 'graduate': 444, 'greece': 445, 'groundwork': 446, 'guerre': 447, 'gunumuze': 448, 'gurun': 449, 'hakkinda': 450, 'halasi': 451, 'halide': 452, 'halil': 453, 'hamelin': 454, 'hamlin': 455, 'hansard': 456, 'happen': 457, 'harb': 458, 'harbe': 459, 'harbi': 460, 'harbinde': 461, 'harbiye': 462, 'harbord': 463, 'hardly': 464, 'hareket': 465, 'hariciye': 466, 'harry': 467, 'hartill': 468, 'harward': 469, 'hatiralar': 470, 'haven': 471, 'hayati': 472, 'hazine': 473, 'hazirliklari': 474, 'heritage': 475, 'heyeti': 476, 'historians': 477, 'history': 478, 'hocaoglu': 479, 'homeland': 480, 'hopkins': 481, 'house': 482, 'hovanessian': 483, 'hovannisian': 484, 'howard': 485, 'hulbe': 486, 'hurewitz': 487, 'icyuzu': 488, 'idare': 489, 'ignorance': 490, 'ihtilaliyesi': 491, 'iii': 492, 'iki': 493, 'ilan': 494, 'ilgili': 495, 'ili': 496, 'illinois': 497, 'ilmi': 498, 'imparatorlugu': 499, 'imparatorluklarindaki': 500, 'imperialism': 501, 'imtiyazat': 502, 'inalcik': 503, 'incontrovertibly': 504, 'independence': 505, 'india': 506, 'indiana': 507, 'indianapolis': 508, 'ingilizce': 509, 'innocent': 510, 'instance': 511, 'institute': 512, 'intelligence': 513, 'international': 514, 'irade': 515, 'islam': 516, 'istanbul': 517, 'ittihad': 518, 'izahat': 519, 'izmir': 520, 'jackh': 521, 'jaeschke': 522, 'james': 523, 'jennings': 524, 'john': 525, 'jon': 526, 'jorge': 527, 'justin': 528, 'justly': 529, 'kadar': 530, 'kafkas': 531, 'kalem': 532, 'kanunu': 533, 'karal': 534, 'kardes': 535, 'kars': 536, 'karsi': 537, 'kartonlar': 538, 'kartonlari': 539, 'katchaznouni': 540, 'kathleen': 541, 'katolik': 542, 'kaynaklari': 543, 'kazemzadeh': 544, 'kazimir': 545, 'kedouri': 546, 'kentucky': 547, 'kerem': 548, 'kery': 549, 'king': 550, 'kirzioglu': 551, 'kitabevi': 552, 'kital': 553, 'knopt': 554, 'komite': 555, 'komitecileri': 556, 'komitelerinin': 557, 'konferansi': 558, 'kun': 559, 'kur': 560, 'kurat': 561, 'kurds': 562, 'kurtulus': 563, 'lagvindan': 564, 'langer': 565, 'laurence': 566, 'lausanne': 567, 'layard': 568, 'leaders': 569, 'legion': 570, 'lenger': 571, 'leonard': 572, 'levant': 573, 'levy': 574, 'lewis': 575, 'library': 576, 'list': 577, 'london': 578, 'look': 579, 'lords': 580, 'los': 581, 'louise': 582, 'louisville': 583, 'lousanne': 584, 'love': 585, 'loyalty': 586, 'lozan': 587, 'macmillan': 588, 'madeline': 589, 'magazine': 590, 'mahsus': 591, 'makaleler': 592, 'malumat': 593, 'mandaville': 594, 'map': 595, 'mark': 596, 'maryland': 597, 'massachusetts': 598, 'masson': 599, 'matbaasi': 600, 'mazbatalari': 601, 'mccarthy': 602, 'meade': 603, 'meclisi': 604, 'mecmuasi': 605, 'meguerditche': 606, 'melbourne': 607, 'member': 608, 'memurine': 609, 'men': 610, 'meray': 611, 'mesele': 612, 'meselesi': 613, 'mesrutiyetten': 614, 'mesulleri': 615, 'mezalim': 616, 'mezalimi': 617, 'michigan': 618, 'middle': 619, 'millet': 620, 'million': 621, 'ministere': 622, 'minnesota': 623, 'minorities': 624, 'minute': 625, 'minutes': 626, 'modern': 627, 'mogan': 628, 'mondros': 629, 'moslem': 630, 'motayef': 631, 'muammer': 632, 'mudafaalari': 633, 'muharrerat': 634, 'muhimme': 635, 'muratoff': 636, 'murdering': 637, 'muslim': 638, 'muslime': 639, 'muslims': 640, 'mustenid': 641, 'muteferrik': 642, 'mutlucag': 643, 'naff': 644, 'nalbandian': 645, 'nasil': 646, 'nationals': 647, 'nazi': 648, 'near': 649, 'neside': 650, 'new': 651, 'newark': 652, 'nezareti': 653, 'nikolayef': 654, 'nin': 655, 'nizamnamesi': 656, 'nubar': 657, 'nun': 658, 'odasi': 659, 'odiselidze': 660, 'office': 661, 'official': 662, 'ohanus': 663, 'olcay': 664, 'old': 665, 'olduklari': 666, 'olson': 667, 'olunacak': 668, 'olunan': 669, 'opponents': 670, 'ordu': 671, 'oregon': 672, 'orel': 673, 'orfisinde': 674, 'organized': 675, 'orient': 676, 'orsay': 677, 'osmaniye': 678, 'osmanli': 679, 'osmanlilardan': 680, 'ottoman': 681, 'ottomane': 682, 'oxford': 683, 'papazian': 684, 'papers': 685, 'paris': 686, 'parliamentary': 687, 'partition': 688, 'pasa': 689, 'patriotism': 690, 'paul': 691, 'paylasilmasi': 692, 'peace': 693, 'pennsylvania': 694, 'perakende': 695, 'personal': 696, 'perverted': 697, 'peter': 698, 'plani': 699, 'policy': 700, 'political': 701, 'politics': 702, 'poly': 703, 'poor': 704, 'population': 705, 'portland': 706, 'powell': 707, 'power': 708, 'praeger': 709, 'premeditated': 710, 'prens': 711, 'preparing': 712, 'press': 713, 'price': 714, 'princeton': 715, 'print': 716, 'prjevalski': 717, 'proclamation': 718, 'professor': 719, 'progress': 720, 'prominent': 721, 'promise': 722, 'propagandasi': 723, 'proven': 724, 'publications': 725, 'publicly': 726, 'published': 727, 'publishers': 728, 'quai': 729, 'question': 730, 'rachel': 731, 'rahmi': 732, 'raporu': 733, 'rawlinson': 734, 'rebirth': 735, 'records': 736, 'reed': 737, 'references': 738, 'regarded': 739, 'regiments': 740, 'reinhart': 741, 'related': 742, 'remains': 743, 'rendered': 744, 'reports': 745, 'republic': 746, 'research': 747, 'rest': 748, 'retreat': 749, 'review': 750, 'revolutionary': 751, 'revolutionnaires': 752, 'richard': 753, 'rising': 754, 'road': 755, 'robert': 756, 'robinson': 757, 'roderic': 758, 'rolleri': 759, 'ronald': 760, 'russia': 761, 'russian': 762, 'rustow': 763, 'rutgers': 764, 'ryan': 765, 'sabahaddin': 766, 'sardarapat': 767, 'sarkis': 768, 'savagely': 769, 'savasi': 770, 'scholarly': 771, 'scholars': 772, 'school': 773, 'science': 774, 'sciences': 775, 'sdpa': 776, 'sebil': 777, 'section': 778, 'sehid': 779, 'seltzer': 780, 'sempozyumu': 781, 'sent': 782, 'sept': 783, 'serdar': 784, 'serves': 785, 'service': 786, 'sevr': 787, 'shaw': 788, 'sifre': 789, 'sir': 790, 'siyasi': 791, 'siyasiye': 792, 'smith': 793, 'sonra': 794, 'sorun': 795, 'sorunu': 796, 'source': 797, 'sources': 798, 'soviet': 799, 'sovyet': 800, 'soyledikleri': 801, 'spiritual': 802, 'spring': 803, 'standards': 804, 'stanford': 805, 'states': 806, 'stephan': 807, 'stewart': 808, 'story': 809, 'struggle': 810, 'studies': 811, 'successful': 812, 'sydney': 813, 'sykes': 814, 'systematic': 815, 'tahassusler': 816, 'taksimi': 817, 'talat': 818, 'talimatname': 819, 'tanzimat': 820, 'tarih': 821, 'tarihi': 822, 'tarihin': 823, 'tarihinde': 824, 'tarihte': 825, 'teblig': 826, 'tedkik': 827, 'telgraflarin': 828, 'terakki': 829, 'teroru': 830, 'terrorism': 831, 'thomas': 832, 'thousands': 833, 'tibor': 834, 'tom': 835, 'toronto': 836, 'toynbee': 837, 'tran': 838, 'trans': 839, 'transcaucasia': 840, 'translation': 841, 'treaty': 842, 'trench': 843, 'tried': 844, 'truebner': 845, 'turk': 846, 'turkey': 847, 'turkish': 848, 'turkiye': 849, 'turkler': 850, 'turklere': 851, 'turkozu': 852, 'turks': 853, 'turquie': 854, 'tutanaklar': 855, 'twerdokhlebof': 856, 'umumi': 857, 'umumiye': 858, 'union': 859, 'united': 860, 'university': 861, 'valuable': 862, 'valyi': 863, 'varandian': 864, 'version': 865, 'vesaike': 866, 'vesikalariyla': 867, 'vesikalarla': 868, 'veysel': 869, 'vii': 870, 'viii': 871, 'vilayet': 872, 'villalta': 873, 'vols': 874, 'volume': 875, 'volumes': 876, 'volunteer': 877, 'volunteers': 878, 'vukela': 879, 'walter': 880, 'war': 881, 'washington': 882, 'way': 883, 'western': 884, 'william': 885, 'window': 886, 'woods': 887, 'world': 888, 'xiv': 889, 'xxxi': 890, 'xxxii': 891, 'yahut': 892, 'yale': 893, 'yaratilir': 894, 'yayin': 895, 'yayinevi': 896, 'year': 897, 'yildiz': 898, 'yollarinda': 899, 'york': 900, 'young': 901, 'yuca': 902, 'zabitlari': 903, 'zilfi': 904, 'colin': 905, 'common': 906, 'definitely': 907, 'fault': 908, 'luckily': 909, 'mind': 910, 'net': 911, 'play': 912, 'puck': 913, 'scrimmage': 914, 'yes': 915, 'account': 916, 'advertise': 917, 'alternator': 918, 'antenna': 919, 'disremember': 920, 'effective': 921, 'electronics': 922, 'geometry': 923, 'ham': 924, 'height': 925, 'higher': 926, 'hit': 927, 'horsepower': 928, 'inefficiencies': 929, 'isn': 930, 'key': 931, 'klystron': 932, 'knew': 933, 'makes': 934, 'megawatt': 935, 'odd': 936, 'pep': 937, 'produces': 938, 'radio': 939, 'real': 940, 'remember': 941, 'sears': 942, 'station': 943, 'takes': 944, 'taking': 945, 'tower': 946, 'transmitted': 947, 'voltages': 948, 'watts': 949, 'ass': 950, 'bargain': 951, 'car': 952, 'considerable': 953, 'death': 954, 'delaying': 955, 'driving': 956, 'earth': 957, 'fools': 958, 'foot': 959, 'fourth': 960, 'frustrated': 961, 'god': 962, 'going': 963, 'inevitable': 964, 'july': 965, 'kill': 966, 'load': 967, 'neck': 968, 'nose': 969, 'practices': 970, 'rids': 971, 'semi': 972, 'somebody': 973, 'stick': 974, 'suppose': 975, 'thank': 976, 'tough': 977, 'wise': 978, 'yearly': 979, 'com': 980, 'copy': 981, 'email': 982, 'game': 983, 'laying': 984, 'looking': 985, 'mahjongg': 986, 'richg': 987, 'send': 988, 'sequent': 989, 'shanghai': 990, 'solitaire': 991, 'thanks': 992, 'tiles': 993, 'amp': 994, 'audio': 995, 'big': 996, 'box': 997, 'corner': 998, 'integrated': 999, 'klipschorns': 1000, 'legends': 1001, 'little': 1002, 'loaded': 1003, 'preamp': 1004, 'presets': 1005, 'solid': 1006, 'speakers': 1007, 'stereo': 1008, 'tuner': 1009, 'unbelieveable': 1010, 'advance': 1011, 'appreciate': 1012, 'built': 1013, 'buy': 1014, 'christmas': 1015, 'controller': 1016, 'disk': 1017, 'drive': 1018, 'edu': 1019, 'father': 1020, 'greatly': 1021, 'help': 1022, 'ide': 1023, 'installed': 1024, 'law': 1025, 'lynn': 1026, 'mankato': 1027, 'mfm': 1028, 'msus': 1029, 'need': 1030, 'parts': 1031, 'place': 1032, 'purchase': 1033, 'reason': 1034, 'responses': 1035, 'seagate': 1036, 'special': 1037, 'vax': 1038, 'ball': 1039, 'bases': 1040, 'billy': 1041, 'broken': 1042, 'btw': 1043, 'cal': 1044, 'compare': 1045, 'doubts': 1046, 'dumped': 1047, 'era': 1048, 'face': 1049, 'fan': 1050, 'favorite': 1051, 'fernando': 1052, 'gets': 1053, 'getting': 1054, 'gonna': 1055, 'good': 1056, 'heard': 1057, 'hulett': 1058, 'injured': 1059, 'knocked': 1060, 'outstanding': 1061, 'ovation': 1062, 'ovations': 1063, 'park': 1064, 'possible': 1065, 'pretty': 1066, 'rangers': 1067, 'recieved': 1068, 'recieving': 1069, 'return': 1070, 'running': 1071, 'stiches': 1072, 'sutcliffe': 1073, 'wasn': 1074, 'yesterday': 1075, 'apr': 1076, 'avoid': 1077, 'boy': 1078, 'cen': 1079, 'comp': 1080, 'confused': 1081, 'diffrent': 1082, 'excerpts': 1083, 'farad': 1084, 'harvey': 1085, 'having': 1086, 'horror': 1087, 'install': 1088, 'jason': 1089, 'mac': 1090, 'misc': 1091, 'netnews': 1092, 'pin': 1093, 'point': 1094, 'ram': 1095, 'sets': 1096, 'simms': 1097, 'size': 1098, 'stories': 1099, 'sys': 1100, 'thought': 1101, 'titus': 1102, 'use': 1103, 'withstanding': 1104, 'able': 1105, 'actions': 1106, 'alter': 1107, 'arc': 1108, 'body': 1109, 'cognizant': 1110, 'comes': 1111, 'comprehend': 1112, 'die': 1113, 'direct': 1114, 'eternal': 1115, 'experience': 1116, 'far': 1117, 'feelings': 1118, 'form': 1119, 'forms': 1120, 'fully': 1121, 'grace': 1122, 'immortality': 1123, 'joy': 1124, 'knowledge': 1125, 'life': 1126, 'lived': 1127, 'lives': 1128, 'moment': 1129, 'opt': 1130, 'ought': 1131, 'perspective': 1132, 'physical': 1133, 'posit': 1134, 'present': 1135, 'recognize': 1136, 'reconstitution': 1137, 'released': 1138, 'restricted': 1139, 'resurrection': 1140, 'sequentially': 1141, 'sledd': 1142, 'souls': 1143, 'thoughts': 1144, 'torment': 1145, 'toto': 1146, 'visit': 1147, 'wether': 1148, 'address': 1149, 'age': 1150, 'alternative': 1151, 'anoynamous': 1152, 'answer': 1153, 'apply': 1154, 'asks': 1155, 'banned': 1156, 'blues': 1157, 'censorship': 1158, 'certain': 1159, 'check': 1160, 'chose': 1161, 'classical': 1162, 'closed': 1163, 'comments': 1164, 'controling': 1165, 'core': 1166, 'country': 1167, 'dance': 1168, 'decide': 1169, 'definition': 1170, 'disclaimer': 1171, 'easy': 1172, 'explanations': 1173, 'female': 1174, 'hard': 1175, 'hello': 1176, 'industry': 1177, 'jazz': 1178, 'kepler': 1179, 'labeled': 1180, 'labeling': 1181, 'listen': 1182, 'listening': 1183, 'lyrics': 1184, 'mail': 1185, 'major': 1186, 'male': 1187, 'matthew': 1188, 'means': 1189, 'metal': 1190, 'miss': 1191, 'mtt': 1192, 'music': 1193, 'objectionable': 1194, 'occupation': 1195, 'offensive': 1196, 'paper': 1197, 'parents': 1198, 'participate': 1199, 'period': 1200, 'person': 1201, 'questions': 1202, 'rap': 1203, 'record': 1204, 'recordings': 1205, 'repairs': 1206, 'reply': 1207, 'rock': 1208, 'room': 1209, 'sales': 1210, 'sig': 1211, 'simply': 1212, 'soft': 1213, 'specifies': 1214, 'suggestions': 1215, 'survey': 1216, 'think': 1217, 'thompson': 1218, 'took': 1219, 'type': 1220, 'unh': 1221, 'bible': 1222, 'bound': 1223, 'fbi': 1224, 'know': 1225, 'koresh': 1226, 'leak': 1227, 'seals': 1228, 'seven': 1229, 'article': 1230, 'cartoon': 1231, 'dan': 1232, 'deleted': 1233, 'local': 1234, 'newspaper': 1235, 'perfect': 1236, 'placed': 1237, 'sunday': 1238, 'alt': 1239, 'better': 1240, 'create': 1241, 'dave': 1242, 'geez': 1243, 'group': 1244, 'hooked': 1245, 'letterman': 1246, 'pov': 1247, 'raytrace': 1248, 'soon': 1249, 'aspect': 1250, 'biblical': 1251, 'ceremonies': 1252, 'christian': 1253,

In [30]:
dataset_corpus_bow = [dataset_dictionary.doc2bow(doc) for doc in dataset_df['Clean_news']]

In [31]:
len(dataset_corpus_bow)

18846

In [32]:
print(dataset_corpus_bow[1])

[(49, 1), (52, 1), (62, 8), (66, 3), (95, 1), (105, 1), (108, 2), (116, 2), (145, 1), (155, 2), (183, 2), (184, 1), (185, 1), (186, 1), (187, 1), (188, 1), (189, 2), (190, 1), (191, 1), (192, 1), (193, 2), (194, 1), (195, 1), (196, 1), (197, 1), (198, 1), (199, 1), (200, 1), (201, 1), (202, 1), (203, 1), (204, 1), (205, 2), (206, 1), (207, 1), (208, 1), (209, 2), (210, 1), (211, 2), (212, 1), (213, 1), (214, 1), (215, 1), (216, 1), (217, 4), (218, 14), (219, 1), (220, 1), (221, 1), (222, 1), (223, 1), (224, 3), (225, 1), (226, 1), (227, 1), (228, 2), (229, 11), (230, 1), (231, 1), (232, 2), (233, 1), (234, 2), (235, 2), (236, 1), (237, 1), (238, 2), (239, 1), (240, 1), (241, 1), (242, 1), (243, 1), (244, 1), (245, 3), (246, 1), (247, 3), (248, 1), (249, 1), (250, 1), (251, 1), (252, 1), (253, 1), (254, 1), (255, 2), (256, 1), (257, 3), (258, 1), (259, 1), (260, 1), (261, 1), (262, 1), (263, 1), (264, 1), (265, 1), (266, 1), (267, 1), (268, 1), (269, 1), (270, 1), (271, 2), (272, 3), (273, 2), (274, 1), (275, 4), (276, 1), (277, 2), (278, 1), (279, 3), (280, 1), (281, 1), (282, 1), (283, 1), (284, 1), (285, 1), (286, 1), (287, 1), (288, 1), (289, 2), (290, 1), (291, 1), (292, 1), (293, 2), (294, 1), (295, 1), (296, 1), (297, 1), (298, 7), (299, 1), (300, 3), (301, 1), (302, 2), (303, 2), (304, 1), (305, 1), (306, 1), (307, 1), (308, 2), (309, 1), (310, 1), (311, 1), (312, 1), (313, 1), (314, 2), (315, 1), (316, 1), (317, 1), (318, 1), (319, 1), (320, 1), (321, 2), (322, 3), (323, 1), (324, 1), (325, 1), (326, 1), (327, 1), (328, 2), (329, 1), (330, 1), (331, 1), (332, 1), (333, 1), (334, 3), (335, 1), (336, 1), (337, 1), (338, 1), (339, 3), (340, 1), (341, 1), (342, 1), (343, 1), (344, 1), (345, 2), (346, 1), (347, 1), (348, 3), (349, 1), (350, 1), (351, 1), (352, 1), (353, 2), (354, 1), (355, 2), (356, 1), (357, 3), (358, 1), (359, 1), (360, 1), (361, 1), (362, 1), (363, 1), (364, 2), (365, 1), (366, 1), (367, 1), (368, 3), (369, 1), (370, 1), (371, 1), (372, 1), (373, 1), (374, 1), (375, 2), (376, 2), (377, 5), (378, 5), (379, 1), (380, 1), (381, 1), (382, 1), (383, 1), (384, 1), (385, 2), (386, 1), (387, 3), (388, 1), (389, 1), (390, 1), (391, 1), (392, 1), (393, 1), (394, 1), (395, 1), (396, 10), (397, 3), (398, 1), (399, 1), (400, 1), (401, 1), (402, 1), (403, 1), (404, 1), (405, 1), (406, 1), (407, 1), (408, 3), (409, 1), (410, 1), (411, 1), (412, 1), (413, 1), (414, 1), (415, 1), (416, 1), (417, 1), (418, 1), (419, 1), (420, 1), (421, 1), (422, 1), (423, 3), (424, 1), (425, 1), (426, 1), (427, 1), (428, 7), (429, 1), (430, 1), (431, 1), (432, 5), (433, 1), (434, 1), (435, 1), (436, 1), (437, 1), (438, 1), (439, 1), (440, 1), (441, 2), (442, 1), (443, 1), (444, 1), (445, 2), (446, 1), (447, 1), (448, 1), (449, 1), (450, 3), (451, 1), (452, 1), (453, 1), (454, 1), (455, 1), (456, 1), (457, 1), (458, 2), (459, 1), (460, 3), (461, 2), (462, 1), (463, 1), (464, 1), (465, 1), (466, 1), (467, 2), (468, 1), (469, 1), (470, 1), (471, 1), (472, 1), (473, 1), (474, 1), (475, 1), (476, 1), (477, 1), (478, 23), (479, 2), (480, 1), (481, 1), (482, 1), (483, 1), (484, 1), (485, 3), (486, 1), (487, 1), (488, 1), (489, 1), (490, 1), (491, 1), (492, 1), (493, 2), (494, 1), (495, 1), (496, 1), (497, 1), (498, 1), (499, 3), (500, 1), (501, 1), (502, 1), (503, 1), (504, 1), (505, 3), (506, 1), (507, 1), (508, 1), (509, 1), (510, 1), (511, 1), (512, 2), (513, 1), (514, 1), (515, 1), (516, 2), (517, 25), (518, 2), (519, 1), (520, 1), (521, 1), (522, 1), (523, 2), (524, 1), (525, 4), (526, 2), (527, 1), (528, 1), (529, 1), (530, 1), (531, 1), (532, 1), (533, 1), (534, 1), (535, 1), (536, 1), (537, 1), (538, 2), (539, 1), (540, 1), (541, 1), (542, 1), (543, 1), (544, 1), (545, 1), (546, 1), (547, 1), (548, 1), (549, 1), (550, 1), (551, 1), (552, 1), (553, 1), (554, 1), (555, 1), (556, 1), (557, 1), (558, 1), (559, 1), (560, 2), (561, 1), (562, 1), (563, 1), (564, 1), (565, 1), (566, 1), (567, 2), (568, 1), (569, 3), (570, 1), (571, 1), (572, 1), (573, 1), (574, 1), (575, 1), (576, 1), (577, 2), (578, 6), (579, 1), (580, 1), (581, 4), (582, 1), (583, 1), (584, 1), (585, 1), (586, 1), (587, 1), (588, 1), (589, 1), (590, 1), (591, 1), (592, 1), (593, 1), (594, 1), (595, 1), (596, 2), (597, 1), (598, 1), (599, 1), (600, 1), (601, 1), (602, 3), (603, 1), (604, 2), (605, 5), (606, 1), (607, 1), (608, 1), (609, 1), (610, 1), (611, 2), (612, 1), (613, 2), (614, 1), (615, 1), (616, 1), (617, 4), (618, 2), (619, 5), (620, 1), (621, 3), (622, 1), (623, 1), (624, 1), (625, 1), (626, 1), (627, 1), (628, 1), (629, 1), (630, 1), (631, 1), (632, 1), (633, 1), (634, 4), (635, 1), (636, 2), (637, 1), (638, 1), (639, 1), (640, 3), (641, 1), (642, 1), (643, 1), (644, 1), (645, 2), (646, 1), (647, 1), (648, 1), (649, 3), (650, 1), (651, 12), (652, 1), (653, 5), (654, 1), (655, 2), (656, 1), (657, 1), (658, 5), (659, 2), (660, 1), (661, 8), (662, 1), (663, 1), (664, 1), (665, 1), (666, 1), (667, 1), (668, 1), (669, 1), (670, 1), (671, 1), (672, 1), (673, 1), (674, 1), (675, 1), (676, 1), (677, 1), (678, 1), (679, 10), (680, 1), (681, 4), (682, 1), (683, 1), (684, 2), (685, 3), (686, 1), (687, 1), (688, 2), (689, 1), (690, 1), (691, 3), (692, 1), (693, 1), (694, 2), (695, 1), (696, 1), (697, 1), (698, 1), (699, 1), (700, 2), (701, 5), (702, 1), (703, 1), (704, 1), (705, 1), (706, 1), (707, 1), (708, 1), (709, 1), (710, 1), (711, 1), (712, 1), (713, 8), (714, 1), (715, 1), (716, 1), (717, 1), (718, 1), (719, 26), (720, 1), (721, 1), (722, 1), (723, 1), (724, 1), (725, 1), (726, 1), (727, 1), (728, 2), (729, 1), (730, 2), (731, 1), (732, 1), (733, 1), (734, 2), (735, 1), (736, 1), (737, 1), (738, 1), (739, 1), (740, 1), (741, 1), (742, 1), (743, 1), (744, 1), (745, 1), (746, 1), (747, 1), (748, 1), (749, 1), (750, 1), (751, 2), (752, 1), (753, 2), (754, 1), (755, 3), (756, 3), (757, 1), (758, 1), (759, 1), (760, 1), (761, 1), (762, 1), (763, 1), (764, 1), (765, 1), (766, 1), (767, 1), (768, 1), (769, 1), (770, 1), (771, 1), (772, 1), (773, 1), (774, 1), (775, 1), (776, 1), (777, 1), (778, 1), (779, 1), (780, 1), (781, 1), (782, 1), (783, 1), (784, 1), (785, 1), (786, 1), (787, 1), (788, 3), (789, 1), (790, 2), (791, 2), (792, 1), (793, 1), (794, 1), (795, 1), (796, 1), (797, 3), (798, 1), (799, 1), (800, 2), (801, 1), (802, 1), (803, 1), (804, 1), (805, 3), (806, 1), (807, 1), (808, 1), (809, 1), (810, 2), (811, 5), (812, 1), (813, 1), (814, 1), (815, 1), (816, 1), (817, 1), (818, 1), (819, 1), (820, 1), (821, 2), (822, 3), (823, 1), (824, 1), (825, 1), (826, 1), (827, 1), (828, 1), (829, 1), (830, 1), (831, 1), (832, 2), (833, 1), (834, 1), (835, 1), (836, 1), (837, 1), (838, 1), (839, 1), (840, 1), (841, 1), (842, 1), (843, 1), (844, 1), (845, 1), (846, 5), (847, 13), (848, 7), (849, 3), (850, 1), (851, 1), (852, 1), (853, 5), (854, 1), (855, 1), (856, 1), (857, 1), (858, 5), (859, 1), (860, 1), (861, 35), (862, 1), (863, 1), (864, 1), (865, 1), (866, 1), (867, 1), (868, 1), (869, 1), (870, 1), (871, 1), (872, 1), (873, 1), (874, 2), (875, 1), (876, 1), (877, 1), (878, 1), (879, 1), (880, 1), (881, 3), (882, 2), (883, 1), (884, 1), (885, 2), (886, 1), (887, 1), (888, 3), (889, 1), (890, 1), (891, 1), (892, 1), (893, 1), (894, 1), (895, 1), (896, 1), (897, 1), (898, 2), (899, 1), (900, 11), (901, 1), (902, 1), (903, 1), (904, 1)]

In [33]:
tfidf = models.TfidfModel(dataset_corpus_bow)
dataset_corpus_tfidf = tfidf[dataset_corpus_bow]

In [34]:
len(dataset_corpus_tfidf)

18846

In [35]:
print(dataset_corpus_tfidf[1])

[(49, np.float64(0.010645834882449553)), (52, np.float64(0.006615130382221056)), (62, np.float64(0.0617100398859919)), (66, np.float64(0.021861456185676868)), (95, np.float64(0.0035816922026613257)), (105, np.float64(0.011910577266839327)), (108, np.float64(0.014793324889919662)), (116, np.float64(0.008805204722479264)), (145, np.float64(0.009739563423712445)), (155, np.float64(0.014787725250348199)), (183, np.float64(0.012344102501304945)), (184, np.float64(0.01556101922900165)), (185, np.float64(0.014769193003074612)), (186, np.float64(0.011566148277886087)), (187, np.float64(0.019677821389647007)), (188, np.float64(0.015241926482258469)), (189, np.float64(0.039355642779294014)), (190, np.float64(0.019677821389647007)), (191, np.float64(0.015241926482258469)), (192, np.float64(0.018554679137569988)), (193, np.float64(0.03478897473898242)), (194, np.float64(0.018873771884313172)), (195, np.float64(0.019677821389647007)), (196, np.float64(0.019677821389647007)), (197, np.float64(0.018873771884313172)), (198, np.float64(0.016753431430117652)), (199, np.float64(0.019677821389647007)), (200, np.float64(0.01390464290134589)), (201, np.float64(0.014036216272903567)), (202, np.float64(0.01705252702323041)), (203, np.float64(0.011502842697284457)), (204, np.float64(0.019677821389647007)), (205, np.float64(0.025814889398454773)), (206, np.float64(0.018873771884313172)), (207, np.float64(0.01924213742646491)), (208, np.float64(0.01827321938770407)), (209, np.float64(0.030483852964516937)), (210, np.float64(0.008658800239414916)), (211, np.float64(0.039355642779294014)), (212, np.float64(0.01924213742646491)), (213, np.float64(0.019677821389647007)), (214, np.float64(0.015027785153422906)), (215, np.float64(0.019677821389647007)), (216, np.float64(0.01648764154567172)), (217, np.float64(0.04841358077557423)), (218, np.float64(0.2178542692060231)), (219, np.float64(0.016248477517896574)), (220, np.float64(0.012448446932453226)), (221, np.float64(0.018873771884313172)), (222, np.float64(0.01758576109880915)), (223, np.float64(0.019677821389647007)), (224, np.float64(0.03943095373217551)), (225, np.float64(0.014649685805903211)), (226, np.float64(0.018554679137569988)), (227, np.float64(0.011837605309447621)), (228, np.float64(0.024850716773047864)), (229, np.float64(0.12776228213331428)), (230, np.float64(0.011715032498111387)), (231, np.float64(0.01924213742646491)), (232, np.float64(0.037109358275139975)), (233, np.float64(0.010850787217597923)), (234, np.float64(0.033506862860235305)), (235, np.float64(0.03654643877540814)), (236, np.float64(0.018554679137569988)), (237, np.float64(0.019677821389647007)), (238, np.float64(0.039355642779294014)), (239, np.float64(0.014323318636757839)), (240, np.float64(0.014374710852184485)), (241, np.float64(0.019677821389647007)), (242, np.float64(0.015027785153422906)), (243, np.float64(0.015027785153422906)), (244, np.float64(0.01603108717984025)), (245, np.float64(0.05481965816311221)), (246, np.float64(0.016753431430117652)), (247, np.float64(0.04001253771216154)), (248, np.float64(0.018873771884313172)), (249, np.float64(0.019677821389647007)), (250, np.float64(0.019677821389647007)), (251, np.float64(0.010119156766850516)), (252, np.float64(0.012718334524528727)), (253, np.float64(0.00713929175623543)), (254, np.float64(0.018554679137569988)), (255, np.float64(0.03478897473898242)), (256, np.float64(0.019677821389647007)), (257, np.float64(0.05903346416894102)), (258, np.float64(0.01924213742646491)), (259, np.float64(0.019677821389647007)), (260, np.float64(0.013206540292340143)), (261, np.float64(0.019677821389647007)), (262, np.float64(0.018873771884313172)), (263, np.float64(0.018554679137569988)), (264, np.float64(0.019677821389647007)), (265, np.float64(0.01924213742646491)), (266, np.float64(0.019677821389647007)), (267, np.float64(0.019677821389647007)), (268, np.float64(0.0177936874802826)), (269, np.float64(0.017217395556657415)), (270, np.float64(0.019677821389647007)), (271, np.float64(0.039355642779294014)), (272, np.float64(0.05566403741270997)), (273, np.float64(0.037109358275139975)), (274, np.float64(0.019677821389647007)), (275, np.float64(0.04899306629476053)), (276, np.float64(0.016248477517896574)), (277, np.float64(0.037109358275139975)), (278, np.float64(0.019677821389647007)), (279, np.float64(0.05903346416894102)), (280, np.float64(0.019677821389647007)), (281, np.float64(0.019677821389647007)), (282, np.float64(0.01924213742646491)), (283, np.float64(0.01705252702323041)), (284, np.float64(0.019677821389647007)), (285, np.float64(0.019677821389647007)), (286, np.float64(0.019677821389647007)), (287, np.float64(0.018021445061991243)), (288, np.float64(0.018021445061991243)), (289, np.float64(0.02182196598555511)), (290, np.float64(0.012227025136816928)), (291, np.float64(0.017217395556657415)), (292, np.float64(0.015477163400006388)), (293, np.float64(0.02316448046074266)), (294, np.float64(0.018873771884313172)), (295, np.float64(0.019677821389647007)), (296, np.float64(0.019677821389647007)), (297, np.float64(0.01739448736949121)), (298, np.float64(0.07362849814349334)), (299, np.float64(0.018873771884313172)), (300, np.float64(0.04011422647730145)), (301, np.float64(0.010119156766850516)), (302, np.float64(0.0320621743596805)), (303, np.float64(0.03129585004257495)), (304, np.float64(0.008326678412042278)), (305, np.float64(0.019677821389647007)), (306, np.float64(0.019677821389647007)), (307, np.float64(0.013271129248866151)), (308, np.float64(0.022530333236890306)), (309, np.float64(0.01924213742646491)), (310, np.float64(0.014894992885682848)), (311, np.float64(0.012907444699227387)), (312, np.float64(0.019677821389647007)), (313, np.float64(0.019677821389647007)), (314, np.float64(0.022202481864212465)), (315, np.float64(0.02089851375412067)), (316, np.float64(0.009478100827476958)), (317, np.float64(0.009784794665190886)), (318, np.float64(0.01924213742646491)), (319, np.float64(0.013739774367918888)), (320, np.float64(0.019677821389647007)), (321, np.float64(0.03185876954230678)), (322, np.float64(0.04075665046380813)), (323, np.float64(0.019677821389647007)), (324, np.float64(0.014128137063701052)), (325, np.float64(0.012164410744694867)), (326, np.float64(0.019677821389647007)), (327, np.float64(0.009412084311089948)), (328, np.float64(0.022021131962892636)), (329, np.float64(0.01556101922900165)), (330, np.float64(0.01758576109880915)), (331, np.float64(0.016753431430117652)), (332, np.float64(0.019677821389647007)), (333, np.float64(0.01169802427034124)), (334, np.float64(0.048411933457880515)), (335, np.float64(0.01827321938770407)), (336, np.float64(0.018554679137569988)), (337, np.float64(0.01603108717984025)), (338, np.float64(0.018554679137569988)), (339, np.float64(0.05903346416894102)), (340, np.float64(0.019677821389647007)), (341, np.float64(0.019677821389647007)), (342, np.float64(0.01924213742646491)), (343, np.float64(0.019677821389647007)), (344, np.float64(0.01924213742646491)), (345, np.float64(0.02336227248612951)), (346, np.float64(0.01648764154567172)), (347, np.float64(0.019677821389647007)), (348, np.float64(0.05903346416894102)), (349, np.float64(0.019677821389647007)), (350, np.float64(0.01924213742646491)), (351, np.float64(0.018021445061991243)), (352, np.float64(0.01924213742646491)), (353, np.float64(0.039355642779294014)), (354, np.float64(0.018554679137569988)), (355, np.float64(0.023821154533678654)), (356, np.float64(0.019677821389647007)), (357, np.float64(0.05903346416894102)), (358, np.float64(0.019677821389647007)), (359, np.float64(0.01705252702323041)), (360, np.float64(0.01613731115262684)), (361, np.float64(0.01758576109880915)), (362, np.float64(0.01556101922900165)), (363, np.float64(0.019677821389647007)), (364, np.float64(0.025385000526072683)), (365, np.float64(0.019677821389647007)), (366, np.float64(0.01583183465875674)), (367, np.float64(0.019677821389647007)), (368, np.float64(0.036310185581680664)), (369, np.float64(0.01827321938770407)), (370, np.float64(0.014769193003074612)), (371, np.float64(0.019677821389647007)), (372, np.float64(0.019677821389647007)), (373, np.float64(0.015738111041835454)), (374, np.float64(0.018554679137569988)), (375, np.float64(0.033233686120096625)), (376, np.float64(0.039355642779294014)), (377, np.float64(0.05213510856303683)), (378, np.float64(0.06124133286845066)), (379, np.float64(0.019677821389647007)), (380, np.float64(0.01924213742646491)), (381, np.float64(0.014374710852184485)), (382, np.float64(0.018873771884313172)), (383, np.float64(0.018554679137569988)), (384, np.float64(0.018021445061991243)), (385, np.float64(0.036042890123982485)), (386, np.float64(0.0177936874802826)), (387, np.float64(0.039338450026256556)), (388, np.float64(0.019677821389647007)), (389, np.float64(0.007111781138368613)), (390, np.float64(0.011251068371571627)), (391, np.float64(0.01648764154567172)), (392, np.float64(0.012692500263036342)), (393, np.float64(0.009491525839830251)), (394, np.float64(0.019677821389647007)), (395, np.float64(0.019677821389647007)), (396, np.float64(0.1739448736949121)), (397, np.float64(0.05406433518597373)), (398, np.float64(0.019677821389647007)), (399, np.float64(0.018554679137569988)), (400, np.float64(0.01924213742646491)), (401, np.float64(0.0177936874802826)), (402, np.float64(0.01924213742646491)), (403, np.float64(0.019677821389647007)), (404, np.float64(0.018873771884313172)), (405, np.float64(0.010985278487125695)), (406, np.float64(0.015738111041835454)), (407, np.float64(0.018873771884313172)), (408, np.float64(0.05481965816311221)), (409, np.float64(0.019677821389647007)), (410, np.float64(0.019677821389647007)), (411, np.float64(0.015097055102461893)), (412, np.float64(0.01827321938770407)), (413, np.float64(0.01924213742646491)), (414, np.float64(0.010235747983289427)), (415, np.float64(0.012993309478247452)), (416, np.float64(0.019677821389647007)), (417, np.float64(0.018873771884313172)), (418, np.float64(0.01417545833110098)), (419, np.float64(0.015027785153422906)), (420, np.float64(0.019677821389647007)), (421, np.float64(0.019677821389647007)), (422, np.float64(0.009893787637028622)), (423, np.float64(0.033586478117802084)), (424, np.float64(0.015396150695574647)), (425, np.float64(0.008611758446421923)), (426, np.float64(0.016248477517896574)), (427, np.float64(0.02021105546522575)), (428, np.float64(0.08030265528993874)), (429, np.float64(0.012248266573690133)), (430, np.float64(0.019677821389647007)), (431, np.float64(0.018873771884313172)), (432, np.float64(0.05983403411912107)), (433, np.float64(0.011631176669116122)), (434, np.float64(0.019677821389647007)), (435, np.float64(0.019677821389647007)), (436, np.float64(0.019677821389647007)), (437, np.float64(0.008542887803242962)), (438, np.float64(0.01408173471417969)), (439, np.float64(0.01924213742646491)), (440, np.float64(0.018554679137569988)), (441, np.float64(0.012408300387546221)), (442, np.float64(0.019677821389647007)), (443, np.float64(0.018873771884313172)), (444, np.float64(0.013947700749392337)), (445, np.float64(0.02835091666220196)), (446, np.float64(0.019677821389647007)), (447, np.float64(0.018873771884313172)), (448, np.float64(0.018873771884313172)), (449, np.float64(0.018873771884313172)), (450, np.float64(0.05481965816311221)), (451, np.float64(0.019677821389647007)), (452, np.float64(0.01924213742646491)), (453, np.float64(0.018873771884313172)), (454, np.float64(0.01924213742646491)), (455, np.float64(0.019677821389647007)), (456, np.float64(0.019677821389647007)), (457, np.float64(0.009011382065573083)), (458, np.float64(0.03654643877540814)), (459, np.float64(0.019677821389647007)), (460, np.float64(0.05903346416894102)), (461, np.float64(0.039355642779294014)), (462, np.float64(0.019677821389647007)), (463, np.float64(0.01924213742646491)), (464, np.float64(0.011351548767491504)), (465, np.float64(0.019677821389647007)), (466, np.float64(0.019677821389647007)), (467, np.float64(0.029071743266511848)), (468, np.float64(0.01689830280991423)), (469, np.float64(0.019677821389647007)), (470, np.float64(0.01924213742646491)), (471, np.float64(0.00859319799650317)), (472, np.float64(0.019677821389647007)), (473, np.float64(0.019677821389647007)), (474, np.float64(0.019677821389647007)), (475, np.float64(0.01483126521801596)), (476, np.float64(0.019677821389647007)), (477, np.float64(0.015317794629452942)), (478, np.float64(0.20149631189878153)), (479, np.float64(0.039355642779294014)), (480, np.float64(0.014374710852184485)), (481, np.float64(0.015738111041835454)), (482, np.float64(0.009159008080733774)), (483, np.float64(0.019677821389647007)), (484, np.float64(0.01739448736949121)), (485, np.float64(0.04394905741770964)), (486, np.float64(0.01924213742646491)), (487, np.float64(0.019677821389647007)), (488, np.float64(0.019677821389647007)), (489, np.float64(0.01924213742646491)), (490, np.float64(0.012448446932453226)), (491, np.float64(0.019677821389647007)), (492, np.float64(0.01164771407708103)), (493, np.float64(0.037747543768626345)), (494, np.float64(0.01924213742646491)), (495, np.float64(0.019677821389647007)), (496, np.float64(0.01924213742646491)), (497, np.float64(0.013271129248866151)), (498, np.float64(0.019677821389647007)), (499, np.float64(0.05903346416894102)), (500, np.float64(0.019677821389647007)), (501, np.float64(0.018873771884313172)), (502, np.float64(0.019677821389647007)), (503, np.float64(0.01924213742646491)), (504, np.float64(0.01924213742646491)), (505, np.float64(0.04042824475204357)), (506, np.float64(0.015097055102461893)), (507, np.float64(0.012851869033589787)), (508, np.float64(0.01603108717984025)), (509, np.float64(0.019677821389647007)), (510, np.float64(0.01164771407708103)), (511, np.float64(0.010838927908325677)), (512, np.float64(0.022587230240146052)), (513, np.float64(0.01226969851926625)), (514, np.float64(0.010075786322045989)), (515, np.float64(0.019677821389647007)), (516, np.float64(0.024328821489389734)), (517, np.float64(0.3740116683098138)), (518, np.float64(0.039355642779294014)), (519, np.float64(0.019677821389647007)), (520, np.float64(0.01827321938770407)), (521, np.float64(0.019677821389647007)), (522, np.float64(0.019677821389647007)), (523, np.float64(0.021515041810834103)), (524, np.float64(0.0177936874802826)), (525, np.float64(0.03440984080625185)), (526, np.float64(0.02587144972517011)), (527, np.float64(0.018554679137569988)), (528, np.float64(0.017217395556657415)), (529, np.float64(0.01739448736949121)), (530, np.float64(0.018873771884313172)), (531, np.float64(0.01924213742646491)), (532, np.float64(0.019677821389647007)), (533, np.float64(0.019677821389647007)), (534, np.float64(0.019677821389647007)), (535, np.float64(0.01924213742646491)), (536, np.float64(0.01603108717984025)), (537, np.float64(0.019677821389647007)), (538, np.float64(0.039355642779294014)), (539, np.float64(0.019677821389647007)), (540, np.float64(0.019677821389647007)), (541, np.float64(0.01827321938770407)), (542, np.float64(0.019677821389647007)), (543, np.float64(0.018873771884313172)), (544, np.float64(0.019677821389647007)), (545, np.float64(0.019677821389647007)), (546, np.float64(0.019677821389647007)), (547, np.float64(0.01613731115262684)), (548, np.float64(0.018873771884313172)), (549, np.float64(0.02089851375412067)), (550, np.float64(0.011010565981446318)), (551, np.float64(0.01924213742646491)), (552, np.float64(0.018873771884313172)), (553, np.float64(0.01924213742646491)), (554, np.float64(0.019677821389647007)), (555, np.float64(0.01924213742646491)), (556, np.float64(0.019677821389647007)), (557, np.float64(0.019677821389647007)), (558, np.float64(0.019677821389647007)), (559, np.float64(0.01924213742646491)), (560, np.float64(0.039355642779294014)), (561, np.float64(0.019677821389647007)), (562, np.float64(0.013947700749392337)), (563, np.float64(0.019677821389647007)), (564, np.float64(0.019677821389647007)), (565, np.float64(0.01924213742646491)), (566, np.float64(0.018873771884313172)), (567, np.float64(0.036042890123982485)), (568, np.float64(0.01924213742646491)), (569, np.float64(0.034369321043289276)), (570, np.float64(0.016616843060048313)), (571, np.float64(0.019677821389647007)), (572, np.float64(0.01583183465875674)), (573, np.float64(0.01827321938770407)), (574, np.float64(0.01739448736949121)), (575, np.float64(0.013271129248866151)), (576, np.float64(0.010497756354253502)), (577, np.float64(0.015459607418047418)), (578, np.float64(0.0783138964741438)), (579, np.float64(0.006489226912725042)), (580, np.float64(0.01603108717984025)), (581, np.float64(0.04727882102543505)), (582, np.float64(0.019677821389647007)), (583, np.float64(0.01613731115262684)), (584, np.float64(0.018873771884313172)), (585, np.float64(0.00911835698769192)), (586, np.float64(0.01689830280991423)), (587, np.float64(0.019677821389647007)), (588, np.float64(0.017217395556657415)), (589, np.float64(0.019677821389647007)), (590, np.float64(0.010701025462933835)), (591, np.float64(0.019677821389647007)), (592, np.float64(0.018554679137569988)), (593, np.float64(0.018554679137569988)), (594, np.float64(0.019677821389647007)), (595, np.float64(0.012205970851599359)), (596, np.float64(0.019105779183405478)), (597, np.float64(0.014223735648089073)), (598, np.float64(0.01448093482497108)), (599, np.float64(0.019677821389647007)), (600, np.float64(0.01924213742646491)), (601, np.float64(0.01827321938770407)), (602, np.float64(0.04909520620300645)), (603, np.float64(0.01705252702323041)), (604, np.float64(0.039355642779294014)), (605, np.float64(0.09838910694823502)), (606, np.float64(0.019677821389647007)), (607, np.float64(0.016753431430117652)), (608, np.float64(0.010528724121294223)), (609, np.float64(0.019677821389647007)), (610, np.float64(0.00917075083612653)), (611, np.float64(0.039355642779294014)), (612, np.float64(0.019677821389647007)), (613, np.float64(0.03848427485292982)), (614, np.float64(0.019677821389647007)), (615, np.float64(0.019677821389647007)), (616, np.float64(0.01827321938770407)), (617, np.float64(0.07309287755081628)), (618, np.float64(0.028646637273515678)), (619, np.float64(0.05113287333586594)), (620, np.float64(0.01924213742646491)), (621, np.float64(0.02994916421909411)), (622, np.float64(0.019677821389647007)), (623, np.float64(0.012879495305600164)), (624, np.float64(0.01390464290134589)), (625, np.float64(0.011631176669116122)), (626, np.float64(0.010319932082896343)), (627, np.float64(0.010497756354253502)), (628, np.float64(0.019677821389647007)), (629, np.float64(0.019677821389647007)), (630, np.float64(0.013991548693631714)), (631, np.float64(0.019677821389647007)), (632, np.float64(0.01924213742646491)), (633, np.float64(0.019677821389647007)), (634, np.float64(0.07871128555858803)), (635, np.float64(0.019677821389647007)), (636, np.float64(0.03443479111331483)), (637, np.float64(0.015027785153422906)), (638, np.float64(0.011237052812838523)), (639, np.float64(0.019677821389647007)), (640, np.float64(0.03342354070085926)), (641, np.float64(0.018554679137569988)), (642, np.float64(0.019677821389647007)), (643, np.float64(0.019677821389647007)), (644, np.float64(0.019677821389647007)), (645, np.float64(0.03654643877540814)), (646, np.float64(0.019677821389647007)), (647, np.float64(0.01739448736949121)), (648, np.float64(0.012495304235981438)), (649, np.float64(0.02776381999536539)), (650, np.float64(0.01924213742646491)), (651, np.float64(0.06108713078276552)), (652, np.float64(0.018554679137569988)), (653, np.float64(0.09838910694823502)), (654, np.float64(0.019677821389647007)), (655, np.float64(0.037747543768626345)), (656, np.float64(0.019677821389647007)), (657, np.float64(0.019677821389647007)), (658, np.float64(0.09136609693852037)), (659, np.float64(0.03654643877540814)), (660, np.float64(0.019677821389647007)), (661, np.float64(0.07715523322279723)), (662, np.float64(0.010518356877641907)), (663, np.float64(0.01739448736949121)), (664, np.float64(0.019677821389647007)), (66

In [36]:
from gensim.models.ldamodel import LdaModel

In [37]:
lda_bow = LdaModel(dataset_corpus_bow,num_topics=20,id2word=dataset_dictionary,passes=10)

In [38]:
lda_topics_bow = lda_bow.print_topics()
for i in lda_topics_bow:
  print(i)

(0, '0.249*"max" + 0.020*"bhj" + 0.019*"giz" + 0.006*"qax" + 0.006*"idle" + 0.006*"biz" + 0.004*"nrhj" + 0.004*"jays" + 0.004*"cdrom" + 0.004*"phillies"')
(1, '0.012*"people" + 0.007*"government" + 0.006*"think" + 0.006*"right" + 0.005*"president" + 0.005*"gun" + 0.004*"state" + 0.004*"going" + 0.004*"law" + 0.004*"know"')
(2, '0.020*"edu" + 0.013*"mail" + 0.010*"ftp" + 0.010*"available" + 0.010*"com" + 0.010*"graphics" + 0.009*"information" + 0.009*"send" + 0.008*"pub" + 0.007*"software"')
(3, '0.030*"god" + 0.017*"jesus" + 0.012*"christ" + 0.011*"israel" + 0.010*"church" + 0.007*"lord" + 0.007*"man" + 0.006*"bible" + 0.006*"jewish" + 0.006*"jews"')
(4, '0.031*"bike" + 0.016*"dod" + 0.012*"dog" + 0.012*"riding" + 0.011*"ride" + 0.008*"motorcycle" + 0.008*"rec" + 0.008*"bikes" + 0.006*"ottawa" + 0.006*"hartford"')
(5, '0.018*"armenian" + 0.016*"armenians" + 0.013*"turkish" + 0.012*"war" + 0.009*"people" + 0.008*"russian" + 0.008*"turkey" + 0.007*"armenia" + 0.007*"muslim" + 0.006*"genocide"')
(6, '0.017*"file" + 0.015*"image" + 0.013*"use" + 0.012*"window" + 0.012*"display" + 0.010*"color" + 0.010*"program" + 0.009*"windows" + 0.008*"files" + 0.008*"server"')
(7, '0.012*"drug" + 0.011*"vitamin" + 0.011*"medical" + 0.010*"health" + 0.009*"use" + 0.008*"drugs" + 0.007*"study" + 0.007*"disease" + 0.006*"pain" + 0.006*"cancer"')
(8, '0.014*"art" + 0.010*"printer" + 0.010*"appears" + 0.010*"new" + 0.009*"book" + 0.008*"cover" + 0.008*"print" + 0.007*"paper" + 0.007*"man" + 0.007*"copies"')
(9, '0.027*"game" + 0.020*"team" + 0.018*"games" + 0.012*"play" + 0.011*"pit" + 0.010*"year" + 0.010*"hockey" + 0.010*"season" + 0.009*"players" + 0.009*"win"')
(10, '0.023*"university" + 0.011*"new" + 0.011*"york" + 0.010*"conference" + 0.008*"press" + 0.007*"professor" + 0.007*"california" + 0.006*"history" + 0.006*"american" + 0.005*"washington"')
(11, '0.052*"key" + 0.026*"encryption" + 0.024*"chip" + 0.020*"keys" + 0.020*"clipper" + 0.015*"security" + 0.011*"algorithm" + 0.011*"escrow" + 0.011*"use" + 0.011*"des"')
(12, '0.018*"drive" + 0.016*"dos" + 0.015*"windows" + 0.014*"card" + 0.011*"scsi" + 0.011*"disk" + 0.009*"mac" + 0.008*"use" + 0.008*"software" + 0.008*"mhz"')
(13, '0.042*"myers" + 0.027*"sale" + 0.016*"offer" + 0.016*"condition" + 0.015*"asking" + 0.015*"shipping" + 0.014*"san" + 0.014*"edu" + 0.011*"colorado" + 0.010*"sell"')
(14, '0.010*"like" + 0.009*"car" + 0.008*"use" + 0.007*"new" + 0.007*"good" + 0.007*"power" + 0.006*"need" + 0.005*"time" + 0.005*"wire" + 0.005*"know"')
(15, '0.012*"people" + 0.009*"think" + 0.008*"believe" + 0.007*"god" + 0.007*"know" + 0.007*"point" + 0.006*"like" + 0.006*"question" + 0.006*"way" + 0.006*"true"')
(16, '0.015*"like" + 0.014*"know" + 0.012*"time" + 0.011*"think" + 0.010*"good" + 0.008*"said" + 0.008*"got" + 0.008*"going" + 0.007*"people" + 0.007*"right"')
(17, '0.011*"edu" + 0.010*"flyers" + 0.010*"soon" + 0.010*"gordon" + 0.009*"pitt" + 0.009*"banks" + 0.009*"surrender" + 0.009*"nubus" + 0.009*"pens" + 0.008*"candida"')
(18, '0.013*"output" + 0.008*"entry" + 0.007*"signal" + 0.007*"include" + 0.007*"int" + 0.006*"input" + 0.006*"function" + 0.006*"voltage" + 0.006*"line" + 0.006*"rules"')
(19, '0.034*"space" + 0.012*"earth" + 0.011*"nasa" + 0.010*"launch" + 0.008*"satellite" + 0.007*"orbit" + 0.007*"moon" + 0.007*"surface" + 0.006*"shuttle" + 0.006*"solar"')

In [39]:
lda_tfidf = LdaModel(dataset_corpus_tfidf,num_topics=20,id2word=dataset_dictionary,passes=10)

In [40]:
lda_topics_tfidf = lda_tfidf.print_topics()
for i in lda_topics_tfidf:
  print(i)

(0, '0.002*"eprom" + 0.001*"shut" + 0.001*"paradise" + 0.001*"gamma" + 0.001*"startup" + 0.001*"marc" + 0.001*"alarm" + 0.001*"easter" + 0.001*"cga" + 0.001*"wfw"')
(1, '0.002*"compile" + 0.002*"pit" + 0.002*"gilmour" + 0.002*"crash" + 0.002*"doug" + 0.002*"abc" + 0.001*"deletion" + 0.001*"exhaust" + 0.001*"scope" + 0.001*"det"')
(2, '0.004*"diamond" + 0.003*"slots" + 0.002*"external" + 0.002*"scripture" + 0.002*"simm" + 0.002*"circuits" + 0.002*"stealth" + 0.002*"antenna" + 0.002*"oscillator" + 0.002*"subscribe"')
(3, '0.004*"kent" + 0.002*"plastic" + 0.002*"dan" + 0.002*"background" + 0.002*"reverse" + 0.002*"bobby" + 0.002*"figures" + 0.002*"music" + 0.002*"carrying" + 0.002*"angels"')
(4, '0.002*"morris" + 0.002*"channel" + 0.002*"clemens" + 0.002*"max" + 0.002*"swap" + 0.002*"accelerator" + 0.002*"characters" + 0.002*"allah" + 0.002*"bucks" + 0.002*"jays"')
(5, '0.005*"armenian" + 0.004*"armenians" + 0.003*"helmet" + 0.003*"turkish" + 0.002*"genocide" + 0.002*"armenia" + 0.002*"shit" + 0.002*"cmos" + 0.002*"shaft" + 0.002*"stock"')
(6, '0.002*"tcp" + 0.002*"muslims" + 0.002*"pitchers" + 0.002*"militia" + 0.002*"abortion" + 0.002*"serbs" + 0.002*"palestine" + 0.002*"bosnian" + 0.001*"morals" + 0.001*"greece"')
(7, '0.003*"montreal" + 0.002*"duo" + 0.002*"hst" + 0.002*"scoring" + 0.002*"coprocessor" + 0.002*"pittsburgh" + 0.002*"pts" + 0.002*"speedstar" + 0.002*"shots" + 0.001*"humor"')
(8, '0.002*"preferably" + 0.002*"cherry" + 0.002*"cartridges" + 0.001*"quoting" + 0.001*"henrik" + 0.001*"fantasy" + 0.001*"deskjet" + 0.001*"heh" + 0.001*"gatech" + 0.001*"pads"')
(9, '0.002*"ticket" + 0.002*"factory" + 0.002*"capacitor" + 0.002*"hitler" + 0.002*"lcd" + 0.001*"correction" + 0.001*"saturn" + 0.001*"interior" + 0.001*"cylinder" + 0.001*"fluid"')
(10, '0.004*"batf" + 0.003*"nasa" + 0.003*"freedom" + 0.003*"court" + 0.003*"atheists" + 0.002*"atheism" + 0.002*"plan" + 0.002*"des" + 0.002*"widget" + 0.002*"americans"')
(11, '0.005*"drive" + 0.004*"number" + 0.004*"game" + 0.004*"com" + 0.003*"card" + 0.003*"scsi" + 0.003*"team" + 0.003*"mhz" + 0.003*"games" + 0.003*"sell"')
(12, '0.003*"irq" + 0.003*"thanx" + 0.003*"pens" + 0.003*"suggestions" + 0.002*"patent" + 0.002*"exe" + 0.002*"computers" + 0.002*"alcohol" + 0.002*"rid" + 0.002*"openwindows"')
(13, '0.004*"know" + 0.004*"like" + 0.004*"people" + 0.004*"think" + 0.003*"good" + 0.003*"time" + 0.003*"god" + 0.003*"use" + 0.003*"thanks" + 0.003*"right"')
(14, '0.002*"blues" + 0.002*"hawks" + 0.002*"vice" + 0.002*"engines" + 0.002*"honest" + 0.002*"ford" + 0.002*"satellites" + 0.002*"gods" + 0.002*"planet" + 0.002*"discrimination"')
(15, '0.003*"baseball" + 0.003*"printer" + 0.002*"heaven" + 0.002*"product" + 0.002*"particular" + 0.002*"books" + 0.002*"putting" + 0.002*"defense" + 0.002*"president" + 0.002*"israeli"')
(16, '0.002*"norton" + 0.002*"lebanese" + 0.001*"viewer" + 0.001*"emm" + 0.001*"indiana" + 0.001*"european" + 0.001*"carl" + 0.001*"label" + 0.001*"alomar" + 0.001*"bored"')
(17, '0.003*"cadre" + 0.003*"geb" + 0.003*"skepticism" + 0.003*"pitt" + 0.003*"shameful" + 0.003*"intellect" + 0.003*"njxp" + 0.003*"surrender" + 0.003*"dsl" + 0.003*"chastity"')
(18, '0.003*"icon" + 0.002*"mission" + 0.002*"rgb" + 0.002*"nist" + 0.002*"warm" + 0.002*"scanner" + 0.001*"tempest" + 0.001*"solar" + 0.001*"icons" + 0.001*"requirements"')
(19, '0.002*"harley" + 0.002*"feds" + 0.001*"davidian" + 0.001*"arrays" + 0.001*"egyptian" + 0.001*"stat" + 0.001*"prize" + 0.001*"abuse" + 0.001*"baseman" + 0.001*"xwindows"')

In [41]:
from gensim.models.lsimodel import LsiModel

In [42]:
lsi_bow = LsiModel(dataset_corpus_bow,num_topics=20,id2word=dataset_dictionary)

In [43]:
lsi_bow_topics = lsi_bow.print_topics()
for i in lsi_bow_topics:
  print(i)

(0, '0.994*"max" + 0.069*"giz" + 0.068*"bhj" + 0.025*"qax" + 0.015*"biz" + 0.014*"nrhj" + 0.014*"bxn" + 0.012*"nuy" + 0.011*"ghj" + 0.011*"zei"')
(1, '0.276*"jpeg" + 0.265*"file" + 0.218*"dos" + 0.217*"image" + 0.206*"edu" + 0.159*"use" + 0.159*"available" + 0.144*"ftp" + 0.132*"graphics" + 0.130*"version"')
(2, '0.792*"dos" + 0.275*"windows" + -0.173*"jpeg" + 0.151*"microsoft" + -0.123*"file" + 0.112*"tcp" + -0.102*"image" + 0.092*"mouse" + 0.079*"amiga" + 0.072*"higher"')
(3, '0.441*"jpeg" + -0.210*"people" + 0.207*"image" + -0.189*"said" + -0.172*"know" + 0.167*"gif" + -0.156*"think" + -0.140*"god" + -0.134*"president" + -0.120*"stephanopoulos"')
(4, '-0.402*"jpeg" + 0.298*"edu" + -0.180*"dos" + 0.173*"pub" + -0.157*"people" + -0.156*"said" + -0.143*"gif" + -0.140*"know" + 0.139*"ftp" + 0.138*"com"')
(5, '-0.396*"god" + -0.382*"jehovah" + -0.304*"lord" + -0.286*"elohim" + 0.252*"file" + -0.180*"christ" + -0.165*"jesus" + -0.146*"father" + 0.131*"president" + 0.128*"stephanopoulos"')
(6, '-0.625*"file" + -0.193*"gun" + -0.160*"jehovah" + 0.159*"image" + -0.149*"god" + 0.135*"stephanopoulos" + 0.134*"edu" + -0.125*"lord" + -0.121*"elohim" + -0.115*"output"')
(7, '0.333*"stephanopoulos" + 0.251*"president" + 0.228*"file" + -0.219*"use" + 0.192*"graphics" + 0.172*"edu" + 0.147*"pub" + 0.145*"think" + -0.116*"wire" + 0.113*"myers"')
(8, '0.174*"stephanopoulos" + -0.174*"new" + -0.157*"hockey" + 0.144*"window" + -0.142*"space" + 0.136*"widget" + -0.117*"league" + 0.115*"subject" + 0.114*"openwindows" + 0.110*"use"')
(9, '0.301*"stephanopoulos" + 0.245*"president" + -0.204*"people" + -0.157*"said" + -0.155*"armenians" + -0.154*"went" + -0.148*"edu" + -0.137*"file" + -0.135*"armenian" + -0.122*"started"')
(10, '-0.240*"hockey" + 0.200*"privacy" + 0.199*"internet" + 0.175*"anonymous" + -0.169*"league" + -0.166*"edu" + -0.156*"team" + -0.156*"nhl" + -0.140*"season" + 0.115*"pub"')
(11, '0.229*"image" + 0.208*"data" + 0.201*"space" + -0.169*"privacy" + -0.154*"jpeg" + -0.153*"internet" + 0.145*"earth" + -0.133*"hockey" + 0.127*"planet" + -0.124*"anonymous"')
(12, '-0.260*"disk" + -0.248*"drive" + -0.185*"hard" + -0.184*"drives" + -0.161*"scsi" + -0.142*"bios" + -0.141*"mac" + -0.141*"rom" + -0.134*"controller" + -0.128*"bit"')
(13, '-0.335*"output" + -0.270*"entry" + -0.208*"program" + 0.168*"gun" + -0.145*"oname" + -0.144*"rules" + -0.140*"contest" + -0.131*"build" + -0.126*"eof" + 0.125*"file"')
(14, '0.305*"wire" + 0.269*"wiring" + 0.159*"ground" + 0.158*"graphics" + 0.154*"neutral" + 0.127*"circuit" + -0.122*"data" + 0.122*"subject" + 0.119*"outlets" + 0.118*"edu"')
(15, '-0.240*"image" + -0.184*"hiv" + 0.169*"space" + -0.166*"health" + 0.155*"disk" + 0.144*"earth" + 0.140*"planet" + -0.138*"cancer" + 0.135*"drive" + -0.129*"medical"')
(16, '0.323*"image" + -0.256*"edu" + -0.203*"com" + -0.194*"hiv" + 0.184*"data" + -0.175*"health" + -0.151*"cancer" + -0.134*"jpeg" + -0.125*"medical" + -0.120*"aids"')
(17, '-0.339*"god" + 0.268*"jehovah" + 0.205*"elohim" + 0.193*"said" + 0.153*"stephanopoulos" + -0.143*"jesus" + 0.116*"lord" + -0.109*"people" + -0.104*"atheists" + 0.102*"hiv"')
(18, '-0.220*"war" + 0.217*"god" + -0.172*"russian" + -0.167*"turkish" + -0.166*"south" + -0.156*"jehovah" + -0.150*"government" + -0.137*"secret" + -0.125*"armenian" + -0.122*"nuclear"')
(19, '0.413*"edu" + 0.391*"com" + -0.258*"graphics" + -0.164*"pub" + -0.153*"ray" + 0.146*"image" + 0.142*"anonymous" + -0.140*"openwindows" + -0.121*"mail" + -0.088*"send"')

In [44]:
lsi_tfidf = LsiModel(dataset_corpus_tfidf,num_topics=20,id2word=dataset_dictionary)

In [45]:
lsi_tfidf_topics = lsi_tfidf.print_topics()
for i in lsi_tfidf_topics:
  print(i)

(0, '0.137*"people" + 0.130*"know" + 0.128*"like" + 0.116*"think" + 0.114*"god" + 0.107*"windows" + 0.105*"use" + 0.099*"good" + 0.097*"time" + 0.097*"thanks"')
(1, '0.278*"god" + -0.241*"windows" + -0.191*"drive" + -0.170*"card" + -0.159*"dos" + -0.144*"thanks" + 0.144*"people" + -0.138*"scsi" + 0.125*"jesus" + -0.106*"file"')
(2, '0.524*"god" + 0.214*"jesus" + -0.195*"game" + 0.155*"windows" + 0.129*"bible" + -0.122*"team" + -0.114*"games" + 0.109*"christ" + -0.106*"year" + 0.100*"dos"')
(3, '0.446*"drive" + 0.356*"scsi" + -0.292*"windows" + 0.189*"ide" + -0.171*"file" + 0.150*"controller" + 0.145*"drives" + 0.136*"hard" + -0.129*"program" + -0.121*"files"')
(4, '0.310*"game" + -0.263*"key" + -0.208*"chip" + 0.196*"games" + 0.176*"team" + -0.175*"encryption" + -0.170*"government" + -0.166*"clipper" + 0.140*"windows" + -0.135*"keys"')
(5, '0.297*"key" + 0.268*"god" + 0.247*"chip" + 0.229*"game" + 0.157*"clipper" + 0.157*"encryption" + -0.142*"israel" + -0.141*"armenian" + 0.140*"keys" + 0.139*"games"')
(6, '-0.343*"windows" + -0.272*"dos" + 0.243*"thanks" + 0.189*"mail" + -0.178*"scsi" + -0.146*"drive" + 0.144*"car" + -0.131*"file" + -0.125*"game" + 0.121*"edu"')
(7, '0.371*"card" + -0.273*"drive" + 0.193*"video" + 0.173*"monitor" + -0.154*"scsi" + -0.150*"geb" + -0.149*"cadre" + -0.148*"dsl" + -0.148*"pitt" + -0.148*"njxp"')
(8, '0.263*"card" + 0.219*"geb" + 0.217*"dsl" + 0.217*"cadre" + 0.216*"njxp" + 0.216*"pitt" + 0.215*"chastity" + 0.213*"skepticism" + 0.213*"intellect" + 0.212*"shameful"')
(9, '-0.354*"car" + 0.196*"thanks" + -0.174*"bike" + -0.169*"windows" + 0.167*"israel" + 0.164*"armenian" + 0.135*"armenians" + 0.131*"mail" + -0.123*"dos" + 0.122*"game"')
(10, '-0.288*"windows" + -0.230*"dos" + 0.166*"scsi" + -0.153*"sale" + -0.136*"thanks" + -0.135*"car" + 0.133*"image" + -0.128*"armenian" + -0.122*"mail" + 0.122*"bit"')
(11, '0.408*"thanks" + 0.187*"know" + 0.167*"advance" + -0.146*"armenian" + 0.134*"scsi" + -0.129*"space" + -0.124*"sale" + 0.123*"windows" + -0.117*"armenians" + -0.101*"offer"')
(12, '-0.256*"armenian" + -0.236*"car" + -0.222*"armenians" + -0.156*"window" + -0.152*"thanks" + -0.136*"turkish" + -0.134*"bike" + -0.134*"key" + -0.127*"god" + 0.115*"com"')
(13, '-0.307*"scsi" + 0.221*"window" + 0.201*"monitor" + 0.173*"israel" + -0.163*"space" + 0.158*"drive" + -0.149*"bus" + -0.144*"drivers" + -0.143*"car" + 0.135*"apple"')
(14, '-0.347*"israel" + -0.238*"mhz" + 0.171*"fbi" + -0.158*"dos" + 0.154*"card" + -0.151*"jews" + 0.145*"file" + 0.143*"drive" + -0.141*"israeli" + 0.140*"monitor"')
(15, '-0.338*"israel" + 0.245*"mhz" + -0.202*"car" + -0.177*"file" + -0.166*"card" + -0.141*"israeli" + 0.132*"com" + -0.130*"jews" + 0.123*"armenian" + -0.121*"arab"')
(16, '0.345*"mhz" + -0.311*"com" + -0.271*"window" + -0.240*"mouse" + 0.173*"file" + -0.173*"scsi" + -0.151*"port" + -0.145*"irq" + -0.136*"modem" + 0.130*"files"')
(17, '-0.349*"scsi" + -0.261*"window" + 0.219*"space" + 0.196*"drive" + 0.149*"card" + -0.143*"gun" + -0.136*"sale" + -0.129*"batf" + -0.128*"fbi" + -0.120*"mhz"')
(18, '-0.279*"scsi" + 0.249*"mhz" + 0.219*"com" + 0.172*"file" + 0.169*"israel" + -0.159*"monitor" + 0.144*"fbi" + 0.137*"bus" + 0.128*"god" + 0.125*"car"')
(19, '0.299*"space" + -0.199*"modem" + 0.196*"window" + -0.183*"file" + -0.179*"com" + -0.179*"mac" + 0.160*"god" + -0.156*"port" + 0.154*"drive" + -0.130*"files"')

In [46]:
!pip install pyLDAvis

Collecting pyLDAvis
  Downloading pyLDAvis-3.4.1-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: numpy>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (1.16.3)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (2.2.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (1.5.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (3.1.6)
Requirement already satisfied: numexpr in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (2.14.1)
Collecting funcy (from pyLDAvis)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (1.6.1)
Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (4.4.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (75.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->pyLDAvis) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->pyLDAvis) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->pyLDAvis) (2026.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->pyLDAvis) (3.6.0)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim->pyLDAvis) (7.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->pyLDAvis) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->pyLDAvis) (1.17.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim->pyLDAvis) (2.2.1)
Downloading pyLDAvis-3.4.1-py3-none-any.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 87.1 MB/s eta 0:00:00
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Installing collected packages: funcy, pyLDAvis
Successfully installed funcy-2.0 pyLDAvis-3.4.1

In [47]:
import pyLDAvis
import pyLDAvis.gensim_models

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [54]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
vis_bow = pyLDAvis.gensim_models.prepare(lda_bow,dataset_corpus_bow,dataset_dictionary)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [55]:
vis_bow

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
1     -0.225648 -0.124760       1        1  14.780507
15    -0.245468 -0.068321       2        1  11.318578
16    -0.224125 -0.116059       3        1  10.205195
2     -0.118245  0.157520       4        1   9.865921
14    -0.231937  0.047962       5        1   9.728372
12    -0.164043  0.190134       6        1   6.042354
3     -0.077327 -0.227708       7        1   5.929233
6     -0.154929  0.197720       8        1   5.688315
9      0.107931 -0.075338       9        1   3.688948
5      0.015426 -0.223833      10        1   3.659399
19     0.031663  0.001655      11        1   3.245434
7      0.006967 -0.002165      12        1   3.154743
18     0.043627  0.121371      13        1   2.296653
10     0.163975 -0.085364      14        1   2.197937
8      0.122990  0.017532      15        1   1.806313
11     0.071819  0.132391      16        1   1.752543
0      0.239293  0.012434      17        1   1.550648
13     0.174414  0.030977      18        1   1.253737
4      0.225972  0.004682      19        1   1.018008
17     0.237646  0.009170      20        1   0.817163, topic_info=        Term         Freq        Total Category  logprob  loglift
7063     max  5960.000000  5960.000000  Default  30.0000  30.0000
962      god  3989.000000  3989.000000  Default  29.0000  29.0000
1019     edu  3629.000000  3629.000000  Default  28.0000  28.0000
1840   space  1940.000000  1940.000000  Default  27.0000  27.0000
931      key  1423.000000  1423.000000  Default  26.0000  26.0000
...      ...          ...          ...      ...      ...      ...
4351  ticket    91.114172   117.242282  Topic20  -4.9301   4.5550
2820    slot    87.154792   141.500709  Topic20  -4.9745   4.3225
1249    soon   121.849752   518.685557  Topic20  -4.6394   3.3586
1019     edu   141.483661  3629.483097  Topic20  -4.4900   1.5624
4000   plane    61.236550   147.078984  Topic20  -5.3274   3.9309

[1208 rows x 6 columns], token_table=       Topic      Freq      Term
term
21984     13  0.039687       abs
21984     18  0.952482       abs
2358       2  0.922367  absolute
2358       4  0.075386  absolute
19253     14  0.980343       adb
...      ...       ...       ...
900       14  0.683813      york
17509     17  0.984279       zei
23607     12  0.982424      zinc
2481       4  0.980599       zip
2481       6  0.017829       zip

[3068 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[2, 16, 17, 3, 15, 13, 4, 7, 10, 6, 20, 8, 19, 11, 9, 12, 1, 14, 5, 18])

In [56]:
vis_tfidf = pyLDAvis.gensim_models.prepare(lda_tfidf,dataset_corpus_tfidf,dataset_dictionary)

In [57]:
vis_tfidf

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
13     0.425598 -0.131654       1        1  44.783566
11     0.187304  0.268698       2        1  16.364982
15    -0.026208  0.065826       3        1   7.703859
10    -0.047038 -0.022821       4        1   4.581911
3     -0.045219 -0.024560       5        1   3.273996
14    -0.037611 -0.015601       6        1   1.986661
12    -0.037984 -0.015470       7        1   1.936154
5     -0.036666 -0.013680       8        1   1.922053
18    -0.034693 -0.012104       9        1   1.670623
9     -0.034306 -0.011731      10        1   1.638216
6     -0.033434 -0.009919      11        1   1.630890
2     -0.033735 -0.012135      12        1   1.598990
17    -0.031944 -0.010666      13        1   1.565519
16    -0.031919 -0.007616      14        1   1.483959
4     -0.031799 -0.008764      15        1   1.438978
1     -0.031242 -0.008648      16        1   1.415783
7     -0.031512 -0.009190      17        1   1.411802
0     -0.029351 -0.006806      18        1   1.218491
8     -0.029349 -0.006803      19        1   1.201293
19    -0.028895 -0.006356      20        1   1.172273, topic_info=          Term        Freq       Total Category  logprob  loglift
1018     drive  101.000000  101.000000  Default  30.0000  30.0000
116     people  175.000000  175.000000  Default  29.0000  29.0000
983       game   76.000000   76.000000  Default  28.0000  28.0000
1803    number   68.000000   68.000000  Default  27.0000  27.0000
1793      card   89.000000   89.000000  Default  26.0000  26.0000
...        ...         ...         ...      ...      ...      ...
3726   hackers    0.603525    1.018777  Topic20  -7.5749   3.9227
8767     vague    0.559664    0.974916  Topic20  -7.6503   3.8912
14302  abiding    0.545266    0.960518  Topic20  -7.6764   3.8800
17617  timmons    0.539553    0.954805  Topic20  -7.6869   3.8755
9085   tapping    0.535208    0.950460  Topic20  -7.6950   3.8719

[799 rows x 6 columns], token_table=       Topic      Freq      Term
term
8193      16  0.774745       abc
14302     20  1.041105   abiding
3011      11  0.867500  abortion
21984     14  0.629753       abs
3577      20  0.666576     abuse
...      ...       ...       ...
11231     20  0.700700  xwindows
16908     12  0.809697    yankee
8563      16  0.810983   yankees
11312      8  0.858443       yep
915        1  0.997767       yes

[915 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[14, 12, 16, 11, 4, 15, 13, 6, 19, 10, 7, 3, 18, 17, 5, 2, 8, 1, 9, 20])

In [58]:
from gensim.models.coherencemodel import CoherenceModel

In [66]:
cm_lsi_bow = CoherenceModel(model=lsi_bow,texts=dataset_df['Clean_news'],dictionary=dataset_dictionary,coherence='u_mass')

In [67]:
print(cm_lsi_bow.get_coherence())

-3.9215240677510033

In [68]:
cm_lda_bow = CoherenceModel(model=lda_bow,texts=dataset_df['Clean_news'],dictionary=dataset_dictionary,coherence='u_mass')

In [69]:
print(cm_lda_bow.get_coherence())

-3.949957739660473

In [70]:
texts = dataset_df['Clean_news']
texts = [x for x in texts if x]

In [72]:
cm_lda_bow_cv = CoherenceModel(model=lda_bow,texts=texts,dictionary=dataset_dictionary,coherence='c_v')
print(cm_lda_bow_cv.get_coherence())

0.608550474011181

In [73]:
cm_lsi_bow_cv = CoherenceModel(model=lsi_bow,texts=texts,dictionary=dataset_dictionary,coherence='c_v')
print(cm_lsi_bow_cv.get_coherence())

0.5069495819410406